language: python
python:
  - "3.6.3"
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test mainapp
  - coverage run --source=mainapp manage.py test mainapp
after_success:
  - coveralls
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=5fb854ed732af075790ccc9d5222e385516e5294c844d85ef9db9bf8b8929081