language: python
python:
  - "3.6.3"
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test mainapp
  - coverage run --source=mainapp manage.py test mainapp
after_success: coveralls